config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from posts.views import home

urlpatterns = [
    path("", home, name="home"),
    path('posts/', include('posts.urls')),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("my_sns.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

my_sns/users/urls.py
from django.urls import path

from my_sns.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

posts/urls.py
from django.urls import path
from . import views

app_name = "posts"
urlpatterns = [
    path('new/', views.new, name="new"),
    path('create/', views.create, name="create"),
    path('<int:id>/edit/', views.edit, name="edit"),
    path('<int:id>/update/', views.update, name="update"),
    path('<int:id>/delete/', views.delete, name="delete"),

    path('<int:post_id>/comment/create', views.comment_create, name="comment_create"),
]

my_sns/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField, ImageField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from posts.models import Post


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)
    image = ImageField(_("Image of User"), upload_to="image/", default="none/default_profile.jpg")

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

    def posts(self):
        return Post.objects.filter(user=self)

posts/models.py
from django.db import models

class Post(models.Model):
    user = models.ForeignKey("users.User", on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    view_count = models.IntegerField(default=0)
    image = models.ImageField(upload_to="images/")

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
       return self.title
    
    def comments(self):
        return Comment.objects.filter(post=self)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey("users.User", on_delete=models.CASCADE)
    body = models.CharField(max_length=300)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.body

my_sns/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):

    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

posts/forms.py
from django import forms
from .models import Post, Comment
from django.utils.translation import gettext_lazy as _

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'image', 'content', 'user']
        labels = {
            'title': "제목",
            'image': "이미지",
            'content': "내용",
        }
        widgets = {
            'user': forms.HiddenInput(),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['user', 'post', 'body']
        labels = {
            'body': "내용",
        }
        widgets = {
            'user': forms.HiddenInput(),
            'post': forms.HiddenInput(),
        }

my_sns/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserListView(LoginRequiredMixin, ListView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_list_view = UserListView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name", "image"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.db.models import Count
import pdb

def home(request):
    posts = Post.objects.all().order_by('-created_at')
    context = {
        'user' : request.user,
        'users_posts_count' : request.user.posts().count(),
        'posts': posts,
        'comment_form': CommentForm(),
    }
    return render(request, 'posts/home.html', context)


def new(request):
    context = {
            'form': PostForm(initial={'user': request.user})
    }
    return render(request, 'posts/new.html', context)


def create(request):
    context = {}
    if request.method == "POST":
       form = PostForm(request.POST, request.FILES or None)
       if form.is_valid():
           form.save()
    return redirect('home')


def edit(request, id):
    post = get_object_or_404(Post, pk=id)
    if 'id' is not None:
        context = {
            'post': post,
            'form': PostForm(instance=post)
        }
        return render(request, 'posts/edit.html', context)


def update(request, id):
    post = get_object_or_404(Post, pk=id)
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES or None, instance=post)
        if form.is_valid():
            form.save()

        return redirect('home')


def delete(request, id):
    post = get_object_or_404(Post, pk=id)
    if request.method == "POST":
        post.delete()

        return redirect('home')
    return redirect('home')



def comment_create(request, post_id):
    if request.method == "POST":
        comment = Comment()
        comment.user = request.user
        comment.post = get_object_or_404(Post, pk=post_id)
        comment.body = request.POST.get('body')
        comment.save()
        return redirect('home')

my_sns/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

my_sns/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}my_sns{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->
    
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    

    <!-- Your stuff: Third-party CSS libraries go here -->
    
    <!-- This file stores project-specific CSS -->
    
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    
    
    {% endblock %}

  </head>

  <body>
    <nav>
      <div class="nav-wrapper">
        <a href="{% url 'home' %}" class="brand-logo">SNS</a>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
          {% if request.user.is_authenticated %}
            <li><a href="{% url 'posts:new' %}">글작성</a></li>
          <!-- users:detail 에서 users 네임스페이스 -->
            <li><a href="{% url 'users:detail' request.user.username  %}">마이페이지</a></li>
            <li><a href="{% url 'account_logout' %}">로그아웃</a></li>
          {% else %}
            <li><a href="{% url 'account_signup' %}">회원가입</a></li>
            <li><a href="{% url 'account_login' %}">로그인</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
  
    <ul class="sidenav" id="mobile-demo">
      {% if request.user.is_authenticated %}
        <li><a href="{% url 'users:detail' request.user.username  %}">마이페이지</a></li>
        <li><a href="{% url 'account_logout' %}">로그아웃</a></li>
      {% else %}
        <li><a href="{% url 'account_signup' %}">회원가입</a></li>
        <li><a href="{% url 'account_login' %}">로그인</a></li>
      {% endif %}
    </ul>
   

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->
      

      <!-- place project specific Javascript in this file -->
      
      <script src="{% static 'js/project.js' %}"></script>
      

    {% endblock javascript %}
  </body>
</html>
 

my_sns/templates/pages/about.html
{% extends "base.html" %}

my_sns/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

my_sns/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <br>
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

my_sns/templates/users/user_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="container">
  <h2>Users</h2>

  <div class="list-group">
    {% for user in user_list %}
      <a href="{% url 'users:detail' user.username %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ user.username }}</h4>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}

posts/templates/posts/edit.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="card col s12">
            <div class="card-content">
                <div class="card-title">글 수정하기</div>
                <br>
                <form action="{% url 'posts:update' post.id %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}

                    <div class="input-field">
                        <input type="submit" class="btn" value="작성하기">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
    

posts/templates/posts/home.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col s12 m4">
            <div class="card">
                <div class="card-image">
                    {% if user.image %}
                        <img src="{{ user.image.url }}" alt="">
                    {% endif %}
                </div>
                <div class="card-content">
                    <div class="card-title">{{ user.name }}</div>
                    <p>이메일 : {{ user.email }}</p>
                    <p>게시물 : {{ users_posts_count }}</p>
                    <p>팔로워 : 3</p>
                    <p>팔로잉 : 3</p>

                    <a href="{% url 'posts:new' %}" class='btn'>글쓰기</a>
                </div>
            </div>
        </div>
        <div class="col s12 m8">
            {% for post in posts %}
                <div class="card post">
                    <div class="card-content">
                        <div class="card-title">
                            {% if post.user.image %}
                                <img src="{{ post.user.image.url }}" alt="" class="circle thumbnail">
                            {% endif %}
                            <span>{{ post.user.name }}</span>
                            <span class="time_font_size right">{{ post.created_at }}</span>
                        </div>
                        <div class="content">
                            {% if user.is_authenticated and user != post.user %}
                                <a href="#" class="btn right">팔로우</a>
                            {% endif %}
                            <div class="card-image">
                                {% if post.image %}
                                    <img src="{{ post.image.url }}" alt="">
                                {% endif %}
                            </div>
                            <p class="pre-line">{{ post.content }}</p>
                        </div>

                    </div>
                    <div class="card-action">
                        <div class="votes-count" data-id="<%= post.id %>">
                            5명이 좋아합니다.
                            <a href="#">좋아요</a>
                            {% if user == post.user %}
                                <form action="{% url 'posts:delete' post.id %}" method="POST">
                                    {% csrf_token %}
                                    <input type="submit" class="right btn" value="삭제">
                                </form>
                                <a href="{% url 'posts:edit' post.id %}" class="right btn" style="margin-right: 8px;">수정</a>
                            {% endif %}
                        </div>

                        <form action="{% url 'posts:comment_create' post_id=post.id %}" method="POST">
                            <div class="input-field">
                                {% csrf_token %}
                                {{ comment_form|crispy }}
                            </div>
                            <div class="input-field">
                                <input type="submit" class="btn" value="댓글 쓰기">
                            </div>
                        </form>

                        {% if post.comments %}
                            <ul class="collection">
                                {% for comment in post.comments %} 
                                    <li class="collection-item" style="padding-bottom: 28px;">
                                        <span class="title">{{ comment.user.name }}</span>
                                        <span class="right">{{ comment.created_at }}</span>
                                        <p class="pre-line">{{ comment.body }}</p>
                                        {% if comment.user == user %}
                                            <div class="right">
                                                삭제
                                            </div>
                                        {% endif %}
                                    </li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    </div>
                </div>                
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}
    

posts/templates/posts/new.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="card col s12">
            <div class="card-content">
                <div class="card-title">새 글 작성하기</div>
                <br>
                <form action="{% url 'posts:create' %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <br>
                    <input type="submit" value="작성" class="btn right">
                    <br>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
    